# Python Exploratory Data Analysis

In [5]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\T L S\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\T L S\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\T L S\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\T L S\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\T L S\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

In [8]:
df=pd.read_csv("cricinfo.csv")

In [9]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [10]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  62 non-null     str
 1   Span    62 non-null     str
 2   Mat     62 non-null     int64
 3   Inns    62 non-null     int64
 4   NO      62 non-null     int64
 5   Runs    62 non-null     int64
 6   HS      62 non-null     str
 7   Ave     62 non-null     float64
 8   BF      62 non-null     str
 9   SR      62 non-null     str
 10  100     62 non-null     int64
 11  50      62 non-null     int64
 12  0       62 non-null     str
 13  4s      62 non-null     int64
 14  6s      62 non-null     int64
dtypes: float64(1), int64(8), str(6)
memory usage: 7.4 KB

In [13]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1

In [14]:
df.tail()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [23]:
df.sample()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
28,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21

In [26]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='str')

In [28]:
df.rename(columns={"Mat":"Matches",},inplace=True)

In [29]:
df

,Player,Span,Matches,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [30]:
df.columns

Index(['Player', 'Span', 'Matches', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF',
       'SR', '100', '50', '0', '4s', '6s'],
      dtype='str')

In [32]:
df.rename(columns={"HS":"High_Score","Ave":"Average_Score","BF":"Ball_face","SR":"Strike_Rate"},inplace=True)

In [33]:
df

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [43]:
df["Country"]=df["Player"].str.split(pat="(").str[1]

In [44]:
df

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS)
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS)
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA)
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS)
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS)
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG)

In [48]:
df["Country"]=df["Country"].str.split(pat=")").str[0]

In [49]:
df

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG

In [52]:
df["High_Score"]=df["High_Score"].str.split(pat="*").str[0]

In [54]:
df["Ball_face"]=df["Ball_face"].str.split(pat="+").str[0]

In [55]:
df

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG

In [60]:
df[df["Strike_Rate"]=="-"]

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,-,15,19,6,258,2,WI
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107,11,WI
54,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144,48.79,-,-,5,6,3,51,0,ENG

In [63]:
df["0"]=df["0"].replace("-",0)

In [64]:
df["Strike_Rate"]=df["Strike_Rate"].replace("-",0)

In [65]:
df["Ball_face"]=df["Ball_face"].replace("-",0)

In [67]:
df.head(62)

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG

In [68]:
df.tail()

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   High_Score     62 non-null     object
 7   Average_Score  62 non-null     float64
 8   Ball_face      62 non-null     object
 9   Strike_Rate    62 non-null     object
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     object
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  Country        62 non-null     object
dtypes: float64(1), int64(8), object(5), str(2)
memory usage: 7.9+ KB

In [72]:
df["High_Score"]=df["High_Score"].astype(int)

In [73]:
df["Ball_face"]=df["Ball_face"].astype(int)

In [74]:
df["Strike_Rate"]=df["Strike_Rate"].astype(float)

In [75]:
df["0"]=df["0"].astype(int)

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   High_Score     62 non-null     int64
 7   Average_Score  62 non-null     float64
 8   Ball_face      62 non-null     int64
 9   Strike_Rate    62 non-null     float64
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     int64
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  Country        62 non-null     object
dtypes: float64(2), int64(11), object(1), str(2)
memory usage: 7.9+ KB

In [81]:
df["starting_year"]=df["Span"].str.split(pat="-").str[0].astype(int)

In [82]:
df["ending_year"]=df["Span"].str.split(pat="-").str[1].astype(int)

In [83]:
df.head()

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country,starting_year,ending_year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI,1930,1954

In [84]:
df["Duration"]=df["ending_year"]-df["starting_year"]

In [85]:
df.head()

,Player,Span,Matches,Inns,NO,Runs,High_Score,Average_Score,Ball_face,Strike_Rate,100,50,0,4s,6s,Country,starting_year,ending_year,Duration
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS,1928,1948,20
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL,2022,2025,3
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016,1
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970,7
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI,1930,1954,24

In [86]:
df.to_csv("cleanedfile.csv")